// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRKg-3VgjDPQEuIQrA7-mNg6NPWUkrzaA',
    appId: '1:1065100430789:web:37a80ef2fe8ac5665a8fac',
    messagingSenderId: '1065100430789',
    projectId: 'assignment09-c2dd1',
    authDomain: 'assignment09-c2dd1.firebaseapp.com',
    storageBucket: 'assignment09-c2dd1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBy3KFB9OJBHMvpsvlNCiVELTYDb2LgMok',
    appId: '1:1065100430789:android:7cedd672c7f3d2e45a8fac',
    messagingSenderId: '1065100430789',
    projectId: 'assignment09-c2dd1',
    storageBucket: 'assignment09-c2dd1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVv6MTNQypS9on_AAyueZI8fR5AOsCa0s',
    appId: '1:1065100430789:ios:fb0b4713d8a2ae2d5a8fac',
    messagingSenderId: '1065100430789',
    projectId: 'assignment09-c2dd1',
    storageBucket: 'assignment09-c2dd1.appspot.com',
    iosBundleId: 'com.example.assignment09',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVv6MTNQypS9on_AAyueZI8fR5AOsCa0s',
    appId: '1:1065100430789:ios:049cec74985247e85a8fac',
    messagingSenderId: '1065100430789',
    projectId: 'assignment09-c2dd1',
    storageBucket: 'assignment09-c2dd1.appspot.com',
    iosBundleId: 'com.example.assignment09.RunnerTests',
  );
}
